# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MunchBunchTruck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MunchBunchTruck
  pod 'Alamofire', '~> 4.5'
  pod 'Moya', '~> 11.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'FontAwesomeKit/FontAwesome'
  pod 'SwiftyJSON'
  pod 'SwiftyBeaver'
  pod 'TwitterKit'
  pod 'GoogleAnalytics'
  pod 'Firebase/Core'
  pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod
  pod 'SwiftKeychainWrapper'
  pod 'ChameleonFramework/Swift', :git =>
  'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4'
end
